---
title: "Dream Team Assignment2"
author: "Benjamin Siglow, Ethan Gruis, Shiv Patel"
date: "11/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Spotify Stats Project
### Ben Siglow, Ethan Gruis, Shiv Patel

```{r Load Data}
library(tidyverse)
# getwd()
# setwd("C://Users//Ben Siglow//Documents//Courses//Bonus code//SpotifyAsvStat")
data <-  read_csv('https://raw.githubusercontent.com/bsiglow/SpotifyAdvStat/master/data.csv')
artist <-  read_csv('https://raw.githubusercontent.com/bsiglow/SpotifyAdvStat/master/data_by_artist.csv')
genres <- read_csv('https://raw.githubusercontent.com/bsiglow/SpotifyAdvStat/master/data_by_genres.csv')
year <- read_csv('https://raw.githubusercontent.com/bsiglow/SpotifyAdvStat/master/data_by_year.csv')
plug <-  read_csv('https://raw.githubusercontent.com/bsiglow/SpotifyAdvStat/master/data_w_genres.csv')
```

# Create Punk and Not Punk DataFrames
```{r Filtering Genres}
library(tidyverse)
punk <- genres %>%
  filter(str_detect(genres, "punk"))

not_punk <- genres %>%
  filter(!str_detect(genres, "punk"))
```

# Initial Exploration
```{r Head Explore}
head(punk)

head(not_punk)
```

```{r Unique Genres}
unique(punk$genres)

# unique(not_punk$genres)
```

```{r Punk Avg}
# Create punk averages dataframe
punk_avg <- data.frame(
  accousticness = mean(punk$acousticness),
  danceability = mean(punk$danceability),
  duration = mean(punk$duration_ms),
  energy = mean(punk$energy),
  instrumentalness = mean(punk$instrumentalness),
  liveness = mean(punk$liveness),
  loudness = mean(punk$loudness),
  speechiness = mean(punk$speechiness),
  tempo = mean(punk$tempo),
  valence = mean(punk$valence),
  popularity = mean(punk$popularity))
head(punk_avg_att)
```

```{r Not Punk Avg}
# Create not-punk averages dataframe
not_punk_avg <- data.frame(
  accousticness = mean(not_punk$acousticness),
  danceability = mean(not_punk$danceability),
  duration = mean(not_punk$duration_ms),
  energy = mean(not_punk$energy),
  instrumentalness = mean(not_punk$instrumentalness),
  liveness = mean(not_punk$liveness),
  loudness = mean(not_punk$loudness),
  speechiness = mean(not_punk$speechiness),
  tempo = mean(not_punk$tempo),
  valence = mean(not_punk$valence),
  popularity = mean(not_punk$popularity))
head(not_punk_avg)
```
# Convert Duration
```{r Duration Conversion}
punk_avg$duration <- punk_avg$duration * (1.667 * 10^(-5))
not_punk_avg$duration <- not_punk_avg$duration * (1.667 * 10^(-5))

```

# Gathering Average DFs
```{r Gather Punk}
punk_acg2 <- gather(punk_avg, key = Attribute, value = Average, na.rm = FALSE,
  convert = FALSE, factor_key = FALSE)
punk_acg2
```
```{r Gather Not-Punk}
not_punk_acg <- gather(not_punk_avg, key = Attribute, value = Average, na.rm = F, convert = F, factor_key = F)
not_punk_acg
```
# Modeling
```{r Generate Punk / Not Punk Indicator for Mixed Model}
genres <- genres %>% mutate(is_punk = ifelse(genres == 'punk', 1, 0))
```

```{r}
library(lme4) 
popularityMixedModel <- lmer(popularity ~ acousticness + 
                             danceability + (loudness | is_punk),
                             data = genres)

summary(popularityMixedModel)
```





